from .autoname import AutoNameByCount
from enum import auto

class Vice(AutoNameByCount):
    """
    Represents a vice.
    """
    lager = auto()
    cider = auto()
    ale = auto()
    moonshine = auto()
    red_wine = auto()
    whiskey = auto()
    martini = auto()
    jagerbomb = auto()
    tequila = auto()
    joint = auto()
    stout = auto()
    margarita = auto()
    gin_tonic = auto()
    bloody_mary = auto()
    screwdriver = auto()
    sake = auto()
    mead = auto()
    white_wine = auto()
    cigar = auto()
    varian_cigar = auto()
    porter = auto()
    energy_drink = auto()
    painkillers = auto()
    mojito = auto()
    bourbon_cola = auto()
    beer = auto()
    spliff = auto()
    stimulants = auto()
    absinthe = auto()
    rum = auto()
    champagne = auto()
    vape_pen = auto()
    sherry = auto()
    espresso = auto()
    water = auto()
    rubbing_alcohol = auto()
    hot_wings = auto()
    antacids = auto()
    smokes = auto()
    vodka = auto()
    maria = auto()
    super_antacids = auto()
    indigos_reserve = auto()